### ISSUE TITLE
Please can you add support for the latests version of confluence

### ISSUE THREAD

**Issue by choffee** [schubergphilis/tableau-confluence-plugin#3]
We are trying to upgrade to 5.8.8 but your plugin only supports 5.7. Is it possible you could update it and make it available in the marketplace.

**Comment by dijikul** [comment]
+1

Upgrading our Confluence broke the plugin's functionality.  How can we help get things working on the updated version of Confluence?

**Comment by roelgerrits** [comment]
It should now work with confluence up to 5.9.4
